### ISSUE TITLE
Remove fallback function

### ISSUE THREAD

**Issue by NickCuso** [FrankNFT-labs/ERC721F#2]
Hey!
It seems this contract should not have a fallback function. The receiver can be okay, in case you want the contract to accept donations for example.

Specifically could you remove this line:
https://github.com/FrankNFT-labs/ERC721F/blob/362ed216133fa831124086394d322ec848b9a927/ERC721F.sol#L100

NFTs with an empty fallback are currently causing issues in our marketplace. We probably need to fix that, but was hoping to understand the rational for why this was added first.

**Comment by FrankNFT-labs** [comment]
The method is there so the contract can indeed receive funds. ex royalties or donations. What marketplace are you talking about?

**Comment by NickCuso** [comment]
`receive()` allows you to accept donations. But why also have `fallback()` -- that's the part that's confusing our market.

foundation.app

**Comment by FrankNFT-labs** [comment]
fallback is used when no method name is specified according to the spec. 
Since when is FND allowing custom contracts? did think they only did deploy there own collections contract template?

**Comment by NickCuso** [comment]
The `receive()` function is used when there's a normal ETH transfer / no method name included. `fallback()` is used when a method is called that's not already implemented by your contract. So externally it looks like your contract supports every method when that's not really the case.

e.g. here we call `.tokenCreator()` https://github.com/f8n/fnd-protocol/blob/main/contracts/mixins/NFTMarketFees.sol#L227 -- the call succeeds but there's no data returned. The `try` block doesn't help us here because the external call worked, but then it attempts to parse the return data and that part reverts in a way we cannot easily try/catch.

FND does import other collections. There are a number of them already on our site and we are working on opening up even more shortly.

**Comment by FrankNFT-labs** [comment]
Interesting, you are calling a non ERC721 method and yes that would go to the fallback indeed and that one does not return any data as by the spec. But that will mean you have a bigger problem here as many custom contracts indeed include both methods to be safe as this is advised as a good practice on the internet for contracts that receive ETH. I will ask advice to some devs in the same space to see how we will handle this.

**Comment by NickCuso** [comment]
I'd love to learn more about this if you have any pointers to where this is recommended. Feel free to tag me on twitter too - @hardlydifficult.

At the end of the day this is now the second contract we've seen do this. I'm sure there are many more. So I have to code around it.

I'm just reaching out for curiosity I guess. I don't understand why any contract would have an empty fallback function - it seems like it will just lead to more issues if it interacts with other contracts at all.  ...maybe there's a benefit I'm not aware of.

thanks!

**Comment by FrankNFT-labs** [comment]
I did base myself on this: https://docs.soliditylang.org/en/v0.8.12/contracts.html
and while not being very explicit it seems to suggest to have both methods.

(Possibly an older version of it when i created the first version on the contract in September last year)

P.S. i'll send you a follow on twitter

**Comment by NickCuso** [comment]
Ah you are referring to that `Warning` block I think. They are trying to say if you have a payable fallback you should also have a receive function. But not the other way around -- it's totally valid / appropriate to include a receive function without the fallback function.

**Comment by FrankNFT-labs** [comment]
Ok, i'll do some tests and implement it. 
thx for all the feedback.
If you see some other GAS improvements (as that is what the ERC721F is all about, feel free to create a PR for it)
