### ISSUE TITLE
Hardhat doesn't support imports via https

### ISSUE THREAD

**Issue by LuigiRetzkowski** [FrankNFT-labs/ERC721F#52]
Maybe its because im a newbie but: If I try to import it like
import "@FrankNFT-labs/ERC721F/blob/v4.7.1/contracts/token/ERC721/ERC721FCOMMON.sol";
like it says in the readme, I get prompted with an Error.

Error HH406: Invalid import https://github.com/FrankNFT-labs/ERC721F/blob/v4.7.1/contracts/token/ERC721/ERC721FCOMMON.sol from contracts/DemoContract2.sol. Hardhat doesn't support imports via https.

Would appreciate a tipp what to do!

**Comment by FrankNFT-labs** [comment]
Hello,

We are working on an NPM pacakage, but that will be for the next release.
If you can't wait for that, "just" copy paste the code of the ERC721FCOMMON.sol, to a new file.
Not ideal, but it will work.

**Comment by LuigiRetzkowski** [comment]
Everything that works, is fine by me. Thank you, and great performance at NFT London!

**Comment by FrankNFT-labs** [comment]
Thank you, i'll close the ticket if it works for you. 
P.S. if you have any improvements or suggestions feel free to make a PR/issue.

**Comment by FrankNFT-labs** [comment]
NPM is now published

**Comment by LuigiRetzkowski** [comment]
Awesome, that was super fast! Thank you so much and ty for the good work!
